### ISSUE TITLE
Polyfill for browser with Native API support but that return no VRDisplays

### ISSUE THREAD

**Issue by toji** [googlevr/webvr-polyfill#177]
As we get closer to having the native WebVR API exposed in some browser there's a possibility that in some cases the native API won't provide any VRDisplays but the polyfill could still function reasonably. Currently in these scenarios having a "WebVR enabled browser" would actually appear to the user as a detriment, because the page would stop providing any WebVR capabilities where before it was able to use the Polyfill at least.

I propose that we refactor the polyfill so that rather than feature checking for the existence of the API and exiting early if it's available it instead patches the native `getVRDisplays` call with a wrapper that checks to see if the promise resolves with an empty array. If so, it supplies a polyfilled VRDisplay instead that functions the same as in the current builds when the native API isn't present at all.

This will probably be something of a short-term concern (hopefully on the order of months), but I feel the reduction in user confusion it would provide during the API's rollout is worthwhile. Any thoughts, objections?

**Comment by marciot** [comment]
Why would it be a "short-term" concern? The WebVR polyfill currently provides two useful benefits. One, it polyfills the WebVR API for browsers that lacks it; and two it provides a convenient virtual VRDisplay for both mobile devices and desktops that lack a VR headset. The first benefit will diminish as more browsers implement the WebVR API, but the second benefit will be indefinite as there will always be many users who lack VR hardware.

The polyfill is providing a great service by not requiring casual game developers to handle the situations in which no native VRDisplay is available and that benefit will still be relevant once the WebVR API is well supported.

**Comment by RikHeijdens** [comment]
This was one of the reasons why we stopped using the `MouseKeyboardVRDisplay`. I would totally support this.

**Comment by marciot** [comment]
For my purposes, it would be sufficient if the MouseKeyboardVRDisplay were made accessible outside the polyfill, so I could write code like this:

var vrDisplay = null;
navigator.getVRDisplays().then(
   function(displays) {
      if(displays.length > 0) {
         vrDisplay = displays[0];
      } else {
         vrDisplay = new MouseKeyboardVRDisplay();
      }
   }
}

Before transitioning my game over to use the WebVR API, I had my own mouse handler but I stripped all that out once I saw that I could get orientation data from the VRDisplay. This was before I realized this what made this work on the desktop was the polyfill and that it wasn't part of the native API.

Even if in the future MouseKeyboardVRDisplay is removed from the polyfill, or in the future the polyfill becomes unnecessary, I'll probably end up keeping MouseKeyboardVRDisplay and using it in my game because it is very convenient to have a common interface regardless of the devices the user may have.

**Comment by kzahel** [comment]
Chrome canary on android has webvr enabled by default (I think...), the presentation examples aren't able to work with cardboard anymore. Or you could change the samples on webvr.info/samples so that they can work on android chrome canary. But I think leaving the samples as-is and updating the polyfill so that it can work in with webvr enabled but no VRDisplays makes more sense, too.

**Comment by autonome** [comment]
Orientation in A-Frame on Firefox Android no longer works correctly since version 52 and it looks like this might be the reason why - the native APIs are present but return no displays.

When will this fix go live?

**Comment by toji** [comment]
@kzahel: The samples should be working again, with slightly changed behavior. Click the "Polyfill" link for any sample will force that sample to use the polyfill, even if a native implementation is available. Clicking the normal link will (as previously) only make use of the native API.

**Comment by marciot** [comment]
@toji Given your comment about the samples, I assume a decision was made not to modify the polyfill to provide MouseKeyboardVRDisplay in the cases in which WebVR is present.

If this is correct, could you let me know what would be the proper way to instantiate a MouseKeyboardVRDisplay on my own using JavaScript code? I tried "new MouseKeyboardVRDisplay()" but it does not appear as if that class is present in the global namespace and I don't know how to access it.

Thank you,

-- Marcio

**Comment by yaustar** [comment]
Was there any progress on this issue or a workaround? Some of my Android devices are now on Chrome 56 so the three.js, samples on the webvr.info and our own do not work on non Daydream devices unless polyfill is forced as no displays are detected.

**Comment by brianchirls** [comment]
It looks like @toji fixed this here 7908ac4002910deeafd967da9033af8234eb3af9 and here 1bf23ee1ce5f0a58b17bff8bdff92eddc0d40b2e but this issue remained open.

However, there appears to be another bug [here](https://github.com/googlevr/webvr-polyfill/blob/master/src/util.js#L391-L392). The polyfill is setting `pose` and `timestamp` properties on a `VRFrameData` object. This is fine if `VRFrameData` is polyfilled (i.e. no WebVR support at all), but if `VRFrameData` is a native object, then its properties are read-only and trying to set them throws an error.

I'm not sure what the best solution is here. I guess you could *always* polyfill `VRFrameData`?

**Comment by jbaicoianu** [comment]
I thought I was also running into this bug, until I realized the problem was that my code was checking to see if the display was an `instanceof VRDisplay`.  This was problematic with the polyfill on browsers which supported WebVR natively, because the polyfill still overwrites the native VRDisplay definition with a pure-JS one, but the `navigator.getVRDisplays()` promise still returns a native object.

Not 100% related to the original bug, but sort of the same issue as the VRFrameData object.  Maybe the overriding of the native classes just needs to happen under a more specific set of circumstances, to avoid this sort of breakage?

**Comment by jbaicoianu** [comment]
I spoke to soon, turns out my problem now is exactly this bug - on non-daydream Android devices running Chrome, the VRFrameData's pose data is always null, because as @brianchirls points out the native implementation's properties are read-only.

I'll do some experiments tonight with always polyfilling VRFrameData and see what breaks.

**Comment by jbaicoianu** [comment]
Turns out aways polyfilling `VRFrameData` doesn't work, because then calling `vrdisplay.getFrameData(framedata)` throws an error about framedata not being an instance of `VRFrameData`.  Argh.

As a work-around, I ended up exporting the polyfilled `VRFrameData` object as `window.WebVRPolyfillFrameData`, and then modified my app to do something like this:

```javascript
var framedata = (vrdisplay.isPolyfilled ? new WebVRPolyfillFrameData() : new VRFrameData());
```

This workaround certainly isn't ideal and is kind of violating the spirit of what a polyfill is so I haven't submitted a pull request, but it works okay as a short-term fix if anyone else's site broke on non-daydream phones once the Android WebVR chrome builds started shipping.

**Comment by brianchirls** [comment]
@jbaicoianu I'm not sure if I can debug this myself, since my non-Daydream S6 phone doesn't reliably connect via USB. But maybe I can offer an idea that you can try?

I don't think conditionally polyfilling is going to work because applications may create a `VRFrameData` before you know whether the cardboard device is available. So I suggest creating a polyfilled `VRFrameData` that also points to a "real" `VRFrameData` object. Then, also polyfill `getFrameData` so that if it's using a native device, run native `getFrameData` on the native `VRFrameData` object and then copy it to the polyfilled `VRFrameData`.

You could probably skip this whole mess if you detect up front that you're not on a mobile device.

**Comment by jsantell** [comment]
Closed via #197
